# Generated by Django 4.2.5 on 2023-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование продукта')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория блюд')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименования блюда')),
                ('text', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('cooking_time', models.CharField(max_length=50, verbose_name='Время готовки')),
                ('energy', models.IntegerField(verbose_name='Энергетическая ценность')),
                ('portion', models.CharField(max_length=50, verbose_name='На сколько человек')),
                ('how_to_cook', models.TextField(max_length=300, verbose_name='Способ приготовления')),
                ('ingredients_for_cook', models.JSONField(blank=True, verbose_name='Ингредиенты для готовки')),
                ('ingredients', models.ManyToManyField(to='api.product', verbose_name='продукты')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('-'), to='api.productcategory', verbose_name='Категория'),
        ),
    ]
