# Generated by Django 4.2.5 on 2023-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=None, max_length=100, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
