# Generated by Django 4.2.5 on 2023-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='catprod/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='catrec/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество за ед.измерения'),
        ),
    ]
