# Generated by Django 4.2.5 on 2023-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_phonenumber_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complied',
            field=models.BooleanField(default=False),
        ),
    ]
