# Generated by Django 4.2.5 on 2023-09-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_ingredients_for_cook_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(verbose_name='Количество за ед.измерения'),
        ),
    ]
